version: "3.7"

services:
  backend:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.10
    restart: always
    env_file:
      - ./.envs/.postgres
    volumes:
      - ./backend:/app

  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./.envs/.postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./_db:/var/lib/postgresql/data

  frontend:
    image: zauberzeug/nicegui
    restart: always
    volumes:
      - ./frontend:/app
    working_dir: /app
