# Generated by Django 4.2.3 on 2023-07-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("receipter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lineitem",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="lineitem",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receipter.unit",
            ),
        ),
    ]
