# Generated by Django 4.2.3 on 2023-08-01 03:45

from django.db import migrations, models
import django.db.models.deletion


def migrate_data(apps, schema_editor):
    Receipt = apps.get_model("receipter", "Receipt")
    for receipt in Receipt.objects.all():
        if receipt.location_alias:
            receipt.location = receipt.location_alias.value
            receipt.save()


class Migration(migrations.Migration):
    dependencies = [
        ("receipter", "0002_alter_lineitem_options_lineitem_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receipter.location",
            ),
        ),
        migrations.RunPython(
            migrate_data, reverse_code=migrations.RunPython.noop
        )
    ]
