# Generated by Django 4.2.3 on 2023-08-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipter", "0003_receipt_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.TextField(),
        ),
    ]
