# Generated by Django 4.2.3 on 2023-07-16 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipter', '0003_alter_lineitem_price_alter_lineitem_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocr_text', models.TextField(db_index=True, editable=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='productalias',
            name='unique_name_per_store',
        ),
        migrations.RemoveConstraint(
            model_name='productcode',
            name='unique_code_per_store',
        ),
        migrations.RenameField(
            model_name='productalias',
            old_name='product',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='productcode',
            old_name='product',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='storealias',
            old_name='store',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='unitalias',
            old_name='unit',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='productalias',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productalias',
            name='store',
        ),
        migrations.RemoveField(
            model_name='productcode',
            name='code',
        ),
        migrations.RemoveField(
            model_name='productcode',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storealias',
            name='name',
        ),
        migrations.RemoveField(
            model_name='unitalias',
            name='text',
        ),
        migrations.AddField(
            model_name='productalias',
            name='ocr_text',
            field=models.TextField(db_index=True, default='', editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productalias',
            name='store_alias',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='receipter.storealias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcode',
            name='ocr_text',
            field=models.TextField(db_index=True, default='', editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcode',
            name='store_alias',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='receipter.storealias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storealias',
            name='ocr_text',
            field=models.TextField(db_index=True, default='', editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitalias',
            name='ocr_text',
            field=models.TextField(db_index=True, default='', editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='productalias',
            constraint=models.UniqueConstraint(fields=('ocr_text', 'store_alias'), name='unique_name_per_store'),
        ),
        migrations.AddConstraint(
            model_name='productcode',
            constraint=models.UniqueConstraint(fields=('ocr_text', 'store_alias'), name='unique_code_per_store'),
        ),
        migrations.AddField(
            model_name='locationalias',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipter.location'),
        ),
    ]
